s3:
  path: "s3://some_host"
  # region_name: 
  # access_key_id
  # secret_access_key:
  bucket_name: "test_bucket"
  chunk_size: 5242880
  max_file_size: 20971520

celery:
  broker: redis://localhost

db:
  uri: "postgresql+asyncpg://postgres:postgres@localhost:5432/uploader_db"